# Generated by Django 5.2.8 on 2025-12-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
    ]
